For each missing day/interval combination we should provide a value. Straighforward approaches would be:

* If an interval `x` is missing on a given day `y`, use the average of (non-missing intervals') steps on day `y` to fill.
* If an interval `x` is missing on a given day `y`, use the average of steps at interval `x` over the other days (where interval `x` is not missing).
* For averages we could use either the mean or the median.

To see why we can't use the the first approach, consider the following plot:

```{r}
p <- ggplot(activity, aes(y = date, x = interval, fill = steps))
p <- p + geom_tile() 
p <- p + scale_x_discrete(breaks = c("0200", "0400", "0600", "0800", 1000, 1200, 1400, 1600, 1800, 2000, 2200))
p <- p + scale_fill_continuous(na.value = "orange")
p <- p + ggtitle("Steps by Day and Interval")
p <- p + xlab("Interval \n(format HHMM)") + ylab("Date")
p <- p + theme_bw()
p
```

This plot is a heatmap of the day vs. interval matrix with orange cells marking missing values. Since the missing values are conditional on the day, we should use the interval averages for imputation.

For the average we will use the mean instead of the median. This is partly arbirtrary and partly suggested by the mean being the best point estimate from a sample to a popluation of measurements.

(Aboue the plot: note that reversing the Date axis would make more sense for a chronological order, but leaving it like this just leaves us with a bit of annoyance; it doesn't influence the purpose of the analysis.)


--------------

```
mfrm$weekday <- ifelse(weekdays(mfrm$date) %in% c("Saturday", "Sunday"), "Weekend", "Weekday")
sfrm.intervals <- summarize(group_by(mfrm, interval, weekday), avg_steps = mean(steps, na.rm = TRUE))
ggplot(sfrm.intervals, aes(x = interval, y = avg_steps)) + geom_point() + scale_x_discrete(breaks = c("0600", 1200, 1800)) + facet_grid(weekday ~ .) + geom_line(aes(group = 1))
```

```
ggplot(sfrm.intervals, aes(x = interval, y = avg_steps, color = weekday)) + geom_point() + scale_x_discrete(breaks = c("0600", 1200, 1800)) + geom_line(aes(group = weekday))
```
